var rule = {
  title: '人人影视',
  host: 'https://svip1.fun',
  url: '/index.php/vod/show/id/fyclass/page/fypage.html',
  searchUrl: 'https://svip1.fun/index.php/vod/search/wd/**.html',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  filter: '',
  filter_url: '',
  filter_def: {},
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  timeout: 5000,
  // class_parse: '.flex.around&&li;a&&Text;a&&href;.*/(.*?).html',
  class_name: '电影&电视剧&动漫&综艺&短剧&动漫电影',
  class_url: '20&21&22&23&24&25',
  cate_exclude: '',
  play_parse: true,
  lazy: $js.toString(() => {
        input = {parse: 1, url: input, js: ''};
    }),
  double: true,
  推荐: '*',
  一级: '.module-items.module-poster-items-base&&a;a&&title;img&&data-original;.div&&Text;a&&href',
  二级: {
    title: 'h1&&Text',
    img: 'img&&data-original',
    desc: '.module-info-tag&&a:lt(4)&&Text',
    content: '.hl-col-xs-12.blurb&&Text',
    tabs: '.module-tab-items-box&&div:gt(0)',
    lists: '.module-play-list&&a',
    tab_text: 'span&&Text',
    list_text: 'span&&Text',
    list_url: 'a&&href',
  },
  搜索: '.module-card-item.module-item;img&&alt;img&&data-original;div&&Text;a&&href',
}